import TypingText from "./TypingText";

/* ===============================
   SHARE CARD GENERATOR
================================ */
async function generateShareCard(text) {
  const canvas = document.createElement("canvas");
  canvas.width = 900;
  canvas.height = 500;

  const ctx = canvas.getContext("2d");

  // background
  const gradient = ctx.createLinearGradient(0, 0, 900, 500);
  gradient.addColorStop(0, "#0a0a12");
  gradient.addColorStop(1, "#16162a");

  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // title
  ctx.fillStyle = "#9d7bff";
  ctx.font = "bold 34px sans-serif";
  ctx.fillText("Cipher", 60, 70);

  // quote text
  ctx.fillStyle = "#ffffff";
  ctx.font = "28px sans-serif";

  const maxWidth = 780;
  const words = text.split(" ");
  let line = "";
  let y = 180;

  for (let i = 0; i < words.length; i++) {
    const testLine = line + words[i] + " ";
    const metrics = ctx.measureText(testLine);

    if (metrics.width > maxWidth) {
      ctx.fillText(line, 60, y);
      line = words[i] + " ";
      y += 40;
    } else {
      line = testLine;
    }
  }

  ctx.fillText(line, 60, y);

  // footer
  ctx.fillStyle = "#888";
  ctx.font = "20px sans-serif";
  ctx.fillText("Generated by Cipher", 60, 450);

  return new Promise((resolve) => {
    canvas.toBlob(resolve);
  });
}

/* ===============================
   SHARE HANDLER
================================ */
async function shareMessage(text) {
  const blob = await generateShareCard(text);
  const file = new File([blob], "cipher-card.png", { type: "image/png" });

  if (navigator.share && navigator.canShare?.({ files: [file] })) {
    await navigator.share({
      files: [file],
      title: "Cipher",
      text: "Generated by Cipher",
    });
  } else {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "cipher-card.png";
    a.click();
  }
}

export default function MessageBubble({
  index,
  role,
  content,
  modelUsed,
  isSelected,
  selectable,
  onSelect,
  transforming,
  isTyping = false,
}) {
  const handleClick = () => {
    if (!selectable) return;
    onSelect?.(index);
  };

  // 🔊 OpenAI Voice Playback
  const handleSpeak = async (e) => {
    e.stopPropagation();
    if (!content) return;

    try {
      const res = await fetch("/api/voice", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: content,
          voice: "alloy",
        }),
      });

      if (!res.ok) throw new Error("Voice request failed");

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      audio.play();
    } catch (err) {
      console.error("Voice playback error:", err);
    }
  };

  const showTyping =
    role === "assistant" && isTyping && (!content || content.trim() === "");

  const shouldAnimate =
    role === "assistant" && isTyping && content && content.trim().length > 0;

  return (
    <div
      className={`cipher-bubble ${role} ${isSelected ? "selected" : ""} ${
        transforming ? "transforming" : ""
      }`}
      onClick={handleClick}
      style={{ cursor: selectable ? "pointer" : "default" }}
    >
      <div className="cipher-text" onClick={handleClick}>
        
      {showTyping ? (
  <div className="cipher-typing">
    <span className="cipher-thinking-label">Cipher is thinking</span>
    <span className="dot"></span>
    <span className="dot"></span>
    <span className="dot"></span>
  </div>
) : role === "assistant" ? (
        ) : role === "assistant" ? (
          shouldAnimate ? (
            <TypingText text={content || ""} />
          ) : (
            content
          )
        ) : (
          content
        )}
      </div>

      {role === "assistant" && content && (
        <div className="cipher-meta">
          {modelUsed && <span className="cipher-model">{modelUsed}</span>}

          <button className="cipher-btn-speak" onClick={handleSpeak}>
            🔊 Speak
          </button>

          <button
            className="cipher-share-btn"
            onClick={() => shareMessage(content)}
          >
            Share
          </button>
        </div>
      )}
    </div>
  );
}
